3-4-2017/MovieDemo/MovieDemo/Models/DemoStudent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MovieDemo.Models
{
    public class DemoStudent
    {
        public String FirstName {
            get; set;
        }
        public String LastName
        {
            get; set;
        }
        public String University
        {
            get; set;
        }

        public String Gender
        {
            get; set;
        }

    }
}

3-4-2017/MovieDemo/MovieDemo/Controllers/DemoStudentController.cs
using MovieDemo.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieDemo.Controllers
{
    public class DemoStudentController : Controller
    {
        // GET: DemoStudent
        public ActionResult Show(DemoStudent receivedUserInput)
        {
            //save to database
            //....
            return View(receivedUserInput);
        }

        public ActionResult Save(DemoStudent model)
        {
            using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                con.Open();
                string query = "Insert into DemoStudent (FirstName, LastName, University, Gender) values('" + model.FirstName + "','" + model.LastName + "','" + model.University + "','" + model.Gender + "')";

                SqlCommand cmd = new SqlCommand(query, con);
                if (cmd.ExecuteNonQuery() == 1)
                    return View("Show", model);
            }
            return View("Show", model);
            //return "Insert Failed!";
        }

        // GET: DemoStudent
        public ActionResult Create()
        {
            return View();
        }
    }
}

3-4-2017/MovieDemo/MovieDemo/Views/DemoStudent/Create.cshtml
@model MovieDemo.Models.DemoStudent
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>



@using (Html.BeginForm("Save","DemoStudent",FormMethod.Post))
{
    @Html.ValidationSummary(excludePropertyErrors: true)

    @Html.LabelFor(model => model.FirstName)
    @Html.EditorFor(model => model.FirstName)
    @Html.ValidationMessageFor(model => model.FirstName)
    <br />

    @Html.LabelFor(model => model.LastName)
    @Html.EditorFor(model => model.LastName)
    @Html.ValidationMessageFor(model => model.LastName)
    <br />

    @Html.LabelFor(model => model.University)
    @Html.EditorFor(model => model.University)
    @Html.ValidationMessageFor(model => model.University)
    <br />

    @Html.DropDownListFor(m => m.Gender, new List<SelectListItem>
                   { new SelectListItem{Text="Male", Value="M"},
                     new SelectListItem{Text="Female", Value="F"}}, "Please select")

    <input type="submit" value="Submit" />

}

3-4-2017/MovieDemo/MovieDemo/Views/DemoStudent/Index.cshtml
@model MovieDemo.Models.DemoStudent
@{
    ViewBag.Title = "Index";
}

@{ 
    String title = Model.Gender == "M" ? "Mr." : "Mrs.";
}

<h2>Welcome, @title @Model.LastName @Model.FirstName From @Model.University University!</h2>

3-4-2017/MovieDemo/MovieDemo/Views/DemoStudent/Show.cshtml
@model MovieDemo.Models.DemoStudent
@{
    ViewBag.Title = "Show";
}

@{
    string title = "Mr.";
    string greeting = "";
    if (Model.Gender == "F")
    {
        title = "Mrs.";
    }
    greeting = "Welcome " + title + " " + Model.LastName + " " + Model.FirstName + " From " + Model.University + " University!";
    ViewBag.Greeting = greeting;
}
<h2>@greeting</h2>